baseURL = "https://beehaa.github.io/blog"
title = "Brian Ha"
paginate = 5
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
googleAnalytics = "UA-123-45"
pygmentsUseClasses = true

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Brian Ha"
description = "my personal blog"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author = "Brian Ha"
images = [ "<link or path of image for opengraph, twitter-cards>" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
showtoc = false
tocopen = false

  [params.assets]
  favicon = "<link / abs url>"
  favicon16x16 = "<link / abs url>"
  favicon32x32 = "<link / abs url>"
  apple_touch_icon = "<link / abs url>"
  safari_pinned_tab = "<link / abs url>"

  [params.label]
  text = "Brian Ha"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false
  title = "ExampleSite"
  subtitle = "This is subtitle"
  imageUrl = "<img location>"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "my image"

    [[params.profileMode.buttons]]
    name = "Posts"
    url = "posts"

    [[params.profileMode.buttons]]
    name = "Tags"
    url = "tags"

  [params.homeInfoParams]
  Title = "Hi, I'm Brian 👋"
  Content = "Welcome to my blog, a digital playground where I let my thoughts run wild and share all sorts of random things. Consider this space my virtual scratch pad, where I jot down whatever comes to mind and let my creativity roam free."

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/brian-ha/"

  [[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/brianhha/"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/beehaa"

[params.analytics.google]
SiteVerificationTag = "XYZabc"

[params.analytics.bing]
SiteVerificationTag = "XYZabc"

[params.analytics.yandex]
SiteVerificationTag = "XYZabc"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "about"
name = "about me"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 20

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 30

[[menu.main]]
identifier = "search"
name = "search"
url = "/search/"
weight = 40


[markup.highlight]
noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]